# Generated by Django 4.1.1 on 2022-09-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_blogpost_comment_profile_delete_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin",
        ),
        migrations.AddField(
            model_name="comment",
            name="comments",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
